version: "3"
services:
  db:
    build: ./docker/db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      dockerfile: $PWD/docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    stdin_open: true
    tty: true
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
  # spa:
  #   build:
  #     context: ./spa
  #     dockerfile: $PWD/docker/spa/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./spa:/spa
  #   stdin_open: true
  #   tty: true
  #   command: ["npm", "start"]
  #   depends_on:
  #     - api
