# Generated by Django 2.2.4 on 2020-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(db_column='client_disponible', default=True),
        ),
    ]
